FROM node:20-alpine
WORKDIR /app/NodeWorker
COPY Page.Ui.SvelteRender/NodeWorker/package.json Page.Ui.SvelteRender/NodeWorker/package-lock.json ./
RUN npm ci --omit=dev && npm cache clean --force
COPY Page.Ui.SvelteRender/NodeWorker/compile.js Page.Ui.SvelteRender/NodeWorker/runner.js ./
USER 1000:1000
ENTRYPOINT ["node", "/app/NodeWorker/runner.js"]
