name: page_ui
description: "Creativity Without Limits"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  animated_text_kit: ^4.3.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.4.3+1
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  font_awesome_flutter: ^10.12.0
  go_router: ^14.8.0
  get_it: ^9.2.0
  google_fonts: ^8.0.1
  graphql_flutter: ^5.2.1
  hive: ^2.2.3
  internet_connection_checker_plus: ^2.0.0
  logger: ^2.6.2
  modal_progress_hud_nsn: ^0.5.1
  pointer_interceptor: ^0.10.1+2
  shared_preferences: ^2.5.4
  skeletonizer: ^2.1.3
  web: ^1.1.0
  youtube_player_iframe: ^5.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.26.3

flutter:
  fonts:
    - family: StoryScript
      fonts:
        - asset: assets/fonts/StoryScript-Regular.ttf
    - family: Audiowide
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
  uses-material-design: true
  assets:
    - assets/images/
flutter_assets:
  assets_path: assets/images/
  output_path: lib/config/themes/
  filename: app_images.dart
  ignore_comments: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logoWithoutBackground.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logoWithoutBackground.png"